### PR TITLE
fix: object client methods can receive dict or list as default_value

### PR DESCRIPTION
**Pull request by federicobond**
## This PR

Updates client object methods to accept dict or list as default value.

### CODE REVIEW

**Review by hlipsig — COMMENTED** [review]
LGTM I don't see anything wrong with it from a code perspective.  This change is straighforward and easy to understand. I'm double checking there's not any obscure reason in our codebase that this shouldn't be done.

**Comment by Kavindu-Dodan** [comment]
@federicobond  can we add few test cases to cover this scenario ? This will help to validate this change as well as not break this with future changes

**Comment by federicobond** [comment]
@Kavindu-Dodan sure! Not sure what kind of tests are you referring to, but I did update the one I found that was missing the list case.

**Comment by federicobond** [comment]
To get proper type testing we would have to run mypy or some other typechecker in some example code, but I think this exceeds the scope of this pull request.

**Review by tcarrio — APPROVED** [review]

**Comment by federicobond** [comment]
Replaced get_object_value for get_object_details in test case. Everything should be green now.

**Review by toddbaert — APPROVED** [review]

**Comment by Kavindu-Dodan** [comment]
> @Kavindu-Dodan sure! Not sure what kind of tests are you referring to, but I did update the one I found that was missing the list case.

Sorry for not being specific. I was referring to the handling list type and seems you already added that.

**Review by Kavindu-Dodan — APPROVED** [review]

**Pull request merged**
