### PR TITLE
chore: replace black, fake8 and isort with ruff and ruff-format

### LINKED ISSUE #219: Consider migrating from flake8/isort to ruff
[ruff](https://github.com/charliermarsh/ruff) is a very fast Python linter written in Rust. It supports a large amount of rules and is being used by more and more high-profile Python projects.

ruff can replace and expand on the tools we are using right now, such as flake8 and isort.

I propose we migrate our current lint configuration to ruff.

### PR DESCRIPTION
**Pull request by gruebel**
## This PR

- replace `black`, `flake8` and `isort` with `ruff` and `ruff-format`
- enabled the rules, which replace `flake8` and the plugins you mentioned in the `pre-commit` config
- additionally enabled some more, which I used in an other project, but feel free to enable more, if something peaks your interest 🙂 
- adjusted GHA to use the `pre-commit` action instead

### Related Issues

Fixes #219

### CODE REVIEW

**Comment by gruebel** [comment]
hey @federicobond and @beeme1mr created a new PR, which only does the ruff addition. Will do the code adjustments in a follow-up PR.

**Review by beeme1mr — APPROVED** [review]

**Comment by beeme1mr** [comment]
Hey @gruebel, sorry for the delay here. Most of the team was out for the holidays. Things should speed up now that people are coming back 😄

**Comment by gruebel** [comment]
@beeme1mr no problem 😄  Fixed the issue with the missing GHA version tag. It looks like they don't offer a shortened variant for it. I usually use commit hashes to pin all GHA versions. Are you interested in it or you want to keep it as is?

**Comment by beeme1mr** [comment]
> @beeme1mr no problem 😄 Fixed the issue with the missing GHA version tag. It looks like they don't offer a shortened variant for it. I usually use commit hashes to pin all GHA versions. Are you interested in it or you want to keep it as is?

I have a slight preference for version tags because they're easier to understand at a glance but I would be fine with either approach.

**Comment by gruebel** [comment]
> I have a slight preference for version tags because they're easier to understand at a glance but I would be fine with either approach.

All good, then let's keep as it is 🙂

**Comment by beeme1mr** [comment]
I'll give @federicobond more time since he's our resident Python expert 😄

**Comment by federicobond** [comment]
Sorry for the delay! I think this is good to merge. It's hard to understand all the implications of moving to a new set of style rules, but this moves us in the right direction regarding tooling, and if it turns out we need to fine-tune the config we can adjust it later.

**Review by federicobond — APPROVED** [review]

**Pull request merged**
