### PR TITLE
chore: update codecov and use OIDC

### PR DESCRIPTION
**Pull request by gruebel**

### CODE REVIEW

**Comment by gruebel** [comment]
ok, that won't work

**Comment by beeme1mr** [comment]
@gruebel do you know why that won't work? Using OIDC would be nice.

**Comment by gruebel** [comment]
@beeme1mr Yeah, basically the GH token can't have the needed permission, when coming from a fork. It would only work for PRs from the same repo.

**Comment by beeme1mr** [comment]
Okay, yeah. That was the issue Todd reported a few months ago. CodeCov doesn't seem to have a great answer for that unfortunately.

**Pull request closed without merging**
